### ISSUE TITLE
(IDEA) adding a 'legend' 

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/staff.targiehandlu.pl#2]
adding icons for example in this section would be really helpful during the event
<img width="1343" alt="image" src="https://github.com/ecommerceberlin/staff.targiehandlu.pl/assets/80756258/feb06f23-07e3-4bd4-836f-299849a9c32b">

**Comment by az** [comment]
i will try to add this later today ....

**Comment by az** [comment]
<img width="1351" alt="25  Targi eHandlu - Warszawa - 11 kwietnia 2024 🔊 2024-04-09 22-56-31" src="https://github.com/ecommerceberlin/staff.targiehandlu.pl/assets/2198/0755ed4e-ec23-422d-b8eb-84f8fea22bd4">
